### ISSUE TITLE
ATAK 4.3 version plugin-examples/plugintemplate compilation fails

### ISSUE THREAD

**Issue by kanagarajan0709** [deptofdefense/AndroidTacticalAssaultKit-CIV#100]
Hi,

I was able to build ATAK Civ 4.3 source.
But the compilation fails for the plugintemplate project as below,

Also I am made some changes suggested from the blog,
https://www.ballantyne.online/developing-atak-plugin-101/

Build file '/home/tess/ATAK/AndroidTacticalAssaultKit-CIV/plugin-examples/plugintemplate/app/build.gradle' line: 85

* What went wrong:
A problem occurred evaluating project ':app'.
> Plugin with id 'atak-takdev-plugin' not found.

But I was able to build sdkplugin example https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/releases/download/4.1.1.4/atak-civ-sdk-4.1.1.4.zip  [https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/issues/27](url)

Do we have any similar atak plugin sdk packages for 4.3 version ? 
AFAIK , both looks almost the same.

**Comment by peterhaigh** [comment]
You select the build variant from the bottom left in Android Studio.  I don't how to do this programmatically.

**Comment by kanagarajan0709** [comment]
> You select the build variant from the bottom left in Android Studio. I don't how to do this programmatically.

Yes that solves the problem with compatibility , able to load the plugin template.
Thank you !

**Comment by kanagarajan0709** [comment]
After the fix from issue #101  [https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/issues/101](url)
 gradle build is OK. 

When I started the app build it seems to fail,

/home/ATAK/AndroidTacticalAssaultKit-CIV/plugin-examples/plugintemplate/app/src/main/java/com/atakmap/android/plugintemplate/PluginTemplateMapComponent.java:6: error: package com.atakmap.android.ipc.AtakBroadcast does not exist
import com.atakmap.android.ipc.AtakBroadcast.DocumentedIntentFilter;

![image](https://user-images.githubusercontent.com/35368270/131896077-f666508c-cb54-4b76-bab3-8233ff10c142.png)

**Comment by peterhaigh** [comment]
Do you have a link to the sdk.path in your local,.properties file?

**Comment by kanagarajan0709** [comment]
> Do you have a link to the sdk.path in your local,.properties file?

Yes , like below:

sdk.dir=/home/Android/Sdk
ndk.dir=/home/ndk/android-ndk-r12b
takDebugKeyFile=keystore/debug.keystore
takDebugKeyFilePassword=android
takDebugKeyAlias=androiddebugkey
takDebugKeyPassword=android
takReleaseKeyFile=...
takReleaseKeyFilePassword=...
takReleaseKeyAlias=...
takReleaseKeyPassword=...

**Comment by peterhaigh** [comment]
No that's the sdk.dir, you need a link to the sd.path.  Like this, I've made my link from the home dir to the ATAK dir

sdk.path=/home/"USER"/"Development DIR"/CivTAK/AndroidTacticalAssaultKit-CIV/atak/ATAK/app/build/libs

Alter the path to suit you and paste it into your local.properties file.

**Comment by kanagarajan0709** [comment]
@peterhaigh thank you !
Able to build and launch the helloworld plugin sample.

**Comment by peterhaigh** [comment]
@kanagarajan0709 Excellent, well done!

**Comment by vivek-lakhataria** [comment]
Hi @peterhaigh 

i have issue in make command
make TARGET=android-arm64-v8a GDAL_USE_KDU=no build_spatialite build_gdal build_commoncommo build_assimp  
make TARGET=android-armeabi-v7a GDAL_USE_KDU=no build_spatialite build_gdal build_commoncommo build_assimp  
make TARGET=android-x86 GDAL_USE_KDU=no build_spatialite build_gdal build_commoncommo build_assimp 
these command are not run correctly and give error about gdal and assimp

**Comment by gitques** [comment]
@peterhaigh 
I have the same error
```
Build file '/home/jk-ubuntu/AndroidTacticalAssaultKit-CIV/plugin-examples/draperplugin/app/build.gradle' line: 94

A problem occurred evaluating project ':app'.
> Plugin with id 'atak-takdev-plugin' not found.
```

So I changed
```
ext.takdevPlugin = getProperty('takdev.plugin', "${rootDir}/../../atak-gradle-takdev.jar")
```
to
```
ext.takdevPlugin = getProperty('takdev.plugin', "/home/jk-ubuntu/AndroidTacticalAssaultKit-CIV/atak-gradle-takdev/gradle/wrapper/gradle-wrapper.jar")
```

because I do not have `AndroidTacticalAssaultKit-CIV/atak-gradle-takdev/build/libs/atak-gradle-takdev-${takdevVersion}.jar`.
Please check [https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/tree/master/atak-gradle-takdev](https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/tree/master/atak-gradle-takdev).

But I am still having the same error.. could you please help?

**Comment by gitques** [comment]
@rob-baily 
While I am trying to build `helloworld`, I have this issue.
If you don't mind, could you please help me out?

**Comment by av-mario** [comment]
Just a note on where the jar is:

If you have gone through Mr Ballantyne's tutorial and have built ATAK, you will have the atak-gradle-takdev.jar. It's located in
```
AndroidTacticalAssaultKit-CIV/atak-gradle-takdev/build/libs/
```
