### ISSUE TITLE
How to build atak-gradle-takdev?

### ISSUE THREAD

**Issue by kanagarajan0709** [deptofdefense/AndroidTacticalAssaultKit-CIV#101]
I understand that atak-gradle-takdev library is used by the plugin framework.
I couldn't find any build info or pre-build binary for 4.3 ATAK source or scripts to generate the library.
I am new to this application development and appreciate for any suggestions/comments from tak developers.

**Comment by peterhaigh** [comment]
Have a read of this excellent how-to.

https://www.ballantyne.online/build-an-atak-dev-environment/

**Comment by kanagarajan0709** [comment]
> Have a read of this excellent page
> 
> https://www.ballantyne.online/build-an-atak-dev-environment/

Yes I have gone through this before and that helped to build & test  ATAK source from scratch.
I couldn't find any details  about how to generate atak-gradle-takdev.jar library needed for plugin development using ATAK-Civ 4.3 source API's.

4.1.1 ATAK-Civ SDK provides prebuilt atak-gradle-takdev.jar library for plugin development usage , that's why the gradle build doesn't have any error for plugintemplate code.

**Comment by peterhaigh** [comment]
If you have gone through Mr Ballantyne's tutorial and have built ATAK, you will have the atak-gradle-takdev.jar.  It's located in

AndroidTacticalAssaultKit-CIV/atak-gradle-takdev/build/libs/

**Comment by kanagarajan0709** [comment]
> If you have gone through Mr Ballantyne's tutorial and have built ATAK, you will have the atak-gradle-takdev.jar. It's located in
> 
> AndroidTacticalAssaultKit-CIV/atak-gradle-takdev/build/libs/

Yes I have built ATAK source and verified on the android device following Mr Ballantyne's tutorial.
But I don't see any build folder within atak-gradle-takdev after the command line build within takthirdparty and app build from android studio. Any Idea in which part of the build this atak-gradle-takedev lib build is triggered ?

**Comment by peterhaigh** [comment]
I think it gets built, as part of the prebuild.sh script?  I could rebuild everything and look at when it pops into existence if you want?

**Comment by kanagarajan0709** [comment]
>> I think it gets built, as part of the prebuild.sh script?
I used the prebuild.sh script - but it doesn't generate the build folder.

>> I could rebuild everything and look at when it pops into existence if
you want?
Yes please if you can confirm.

**Comment by peterhaigh** [comment]
Just been playing around with the code, navigate into atak-gradle-takdev and build it manually.

./gradlew assemble

**Comment by kanagarajan0709** [comment]
> Just been playing around with the code, navigate into atak-gradle-takdev and build it manually.
> 
> ./gradlew assemble

It works.
Thank you very much !!!
