### ISSUE TITLE
ATAK 4.4 SDK - Third Party pipeline, :app:minifyCivReleaseWithProguard FAILED libraryclass depends on program class

### ISSUE THREAD

**Issue by simon-xisystems** [deptofdefense/AndroidTacticalAssaultKit-CIV#102]
I am writing a plugin for release, that depends on Kotlin, I have successfully built de-bug and tested the plugin fine, however when using the Third Party pipeline, I get the following;

Warning: library class androidx.activity.ComponentActivity$4 extends or implements program class androidx.lifecycle.LifecycleEventObserver
Warning: library class androidx.activity.ComponentActivity$5 extends or implements program class androidx.lifecycle.LifecycleEventObserver
Warning: library class androidx.activity.result.ActivityResultRegistry$1 extends or implements program class androidx.lifecycle.LifecycleEventObserver
Warning: library class androidx.fragment.app.DefaultSpecialEffectsController$3 extends or implements program class androidx.core.os.CancellationSignal$OnCancelListener
Warning: library class androidx.fragment.app.DefaultSpecialEffectsController$5 extends or implements program class androidx.core.os.CancellationSignal$OnCancelListener
Warning: library class androidx.fragment.app.DialogFragment$4 extends or implements program class androidx.lifecycle.Observer
Warning: library class androidx.fragment.app.DialogFragment$5 extends or implements program class androidx.fragment.app.FragmentContainer
Warning: library class androidx.fragment.app.Fragment$5 extends or implements program class androidx.lifecycle.LifecycleEventObserver
Warning: library class androidx.fragment.app.Fragment$6 extends or implements program class androidx.arch.core.util.Function
Warning: library class androidx.fragment.app.Fragment$7 extends or implements program class androidx.arch.core.util.Function
Warning: library class androidx.fragment.app.FragmentActivity$1 extends or implements program class androidx.savedstate.SavedStateRegistry$SavedStateProvider
Warning: library class androidx.fragment.app.FragmentAnim$1 extends or implements program class androidx.core.os.CancellationSignal$OnCancelListener
Warning: library class androidx.fragment.app.FragmentManager$1 extends or implements program class androidx.activity.OnBackPressedCallback
Warning: library class androidx.fragment.app.FragmentManager$3 extends or implements program class androidx.fragment.app.FragmentFactory
Warning: library class androidx.fragment.app.FragmentManager$6 extends or implements program class androidx.lifecycle.LifecycleEventObserver
Warning: library class androidx.fragment.app.FragmentManager$StartEnterTransitionListener extends or implements program class androidx.fragment.app.Fragment$OnStartEnterTransitionListener
Warning: library class androidx.fragment.app.SpecialEffectsController$Operation$1 extends or implements program class androidx.core.os.CancellationSignal$OnCancelListener
Warning: library class androidx.lifecycle.AbstractSavedStateViewModelFactory extends or implements program class androidx.lifecycle.ViewModelProvider$KeyedFactory
Warning: library class androidx.lifecycle.SavedStateHandle$1 extends or implements program class androidx.savedstate.SavedStateRegistry$SavedStateProvider
Warning: library class androidx.lifecycle.SavedStateHandle$SavingStateLiveData extends or implements program class androidx.lifecycle.MutableLiveData
Warning: library class androidx.lifecycle.SavedStateHandleController extends or implements program class androidx.lifecycle.LifecycleEventObserver
Warning: library class androidx.lifecycle.SavedStateHandleController$1 extends or implements program class androidx.lifecycle.LifecycleEventObserver
Warning: library class androidx.lifecycle.SavedStateHandleController$OnRecreation extends or implements program class androidx.savedstate.SavedStateRegistry$AutoRecreated
Warning: library class androidx.lifecycle.SavedStateViewModelFactory extends or implements program class androidx.lifecycle.ViewModelProvider$KeyedFactory
Warning: library class com.atakmap.android.bloodhound.ui.BloodHoundRouteWidget$1$3 extends or implements program class androidx.core.util.Consumer
Warning: library class com.atakmap.android.bloodhound.util.BloodHoundToolLink$5 extends or implements program class androidx.core.util.Consumer
Warning: library class com.atakmap.android.bloodhound.util.BloodHoundToolLink$9 extends or implements program class androidx.core.util.Consumer
Warning: library class com.atakmap.android.chat.ConversationFragment extends or implements program class androidx.fragment.app.Fragment
Warning: library class com.atakmap.android.contact.ContactDetailDropdown$6 extends or implements program class androidx.viewpager.widget.ViewPager$SimpleOnPageChangeListener
Warning: library class com.atakmap.android.contact.ContactDetailDropdown$ContactDetailViewAdapter extends or implements program class androidx.fragment.app.FragmentPagerAdapter
Warning: library class com.atakmap.android.contact.ContactDetailView extends or implements program class androidx.fragment.app.Fragment
Warning: library class com.atakmap.android.dropdown.GenericFragmentAdapter extends or implements program class androidx.fragment.app.Fragment
Warning: library class com.atakmap.android.features.FeatureEditDetailsView$1 extends or implements program class androidx.viewpager.widget.PagerAdapter
Warning: library class com.atakmap.android.metrics.activity.MetricFragmentActivity extends or implements program class androidx.fragment.app.FragmentActivity
Warning: library class com.atakmap.android.user.EnterLocationDropDownReceiver$10 extends or implements program class androidx.viewpager.widget.ViewPager$SimpleOnPageChangeListener
Warning: library class com.atakmap.android.user.EnterLocationDropDownReceiver$IconPalletAdapter extends or implements program class androidx.fragment.app.FragmentPagerAdapter
Warning: library class com.atakmap.android.user.icon.Icon2525cPalletFragment extends or implements program class androidx.fragment.app.Fragment
Warning: library class com.atakmap.android.user.icon.MissionSpecificPalletFragment extends or implements program class androidx.fragment.app.Fragment
Warning: library class com.atakmap.android.user.icon.SpotMapPalletFragment extends or implements program class androidx.fragment.app.Fragment
Warning: library class com.atakmap.android.user.icon.UserIconPalletFragment extends or implements program class androidx.fragment.app.Fragment
Warning: library class com.atakmap.android.user.icon.VehiclePalletFragment extends or implements program class androidx.fragment.app.Fragment
Warning: library class com.atakmap.android.vehicle.model.ui.VehicleModelPalletFragment extends or implements program class androidx.fragment.app.Fragment
Warning: library class com.atakmap.android.dropdown.DropDownReceiver depends on program class androidx.fragment.app.Fragment
Warning: library class com.atakmap.android.dropdown.DropDownReceiver depends on program class androidx.fragment.app.Fragment
Warning: library class com.atakmap.android.dropdown.DropDownReceiver depends on program class androidx.fragment.app.Fragment
Warning: library class com.atakmap.android.dropdown.DropDownReceiver depends on program class androidx.fragment.app.Fragment

Warning: there were 47 instances of library classes depending on program classes.
         You must avoid such dependencies, since the program classes will
         be processed, while the library classes will remain unchanged.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#dependency)

After looking at this, I assume this is an issue where the androidx libraries are normally pulled from main.jar and now that I have introduced implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version Proguard is struggling? 

Has this been solved by anyone publishing plugins?

**Comment by peterhaigh** [comment]
I had the same issues, ended up rolling back from the PlayStore version and settling on 4.3.0, until we get an update to 4.4 in Github.

**Comment by peterhaigh** [comment]
Updating to Arctic Fox also has issues with Plugin Dev.

**Comment by simon-xisystems** [comment]
@peterhaigh I still get similar issues with 4.3, what proguard/gradle config are you using for including Kotlin?

**Comment by peterhaigh** [comment]
Module build .gradle settings 

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'
apply plugin: 'kotlinx-serialization'

kotlinOptions {
        jvmTarget = "1.8"
}

dependencies {
    .....
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    .....
}

and 
Project build.gradle
ext.kotlin_version = '1.5.20'


dependencies {
        ......
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
    }

**Comment by simon-xisystems** [comment]
@peterhaigh thanks - turns out regressing the Kotlin plugin to 1.5.20 fixed my issues along with adding, 

-dontwarn module-info
-dontwarn androidx.**

to the proguard file fixed the issue.
