### ISSUE TITLE
SDK support for generating and signing App Bundle for play store. 

### ISSUE THREAD

**Issue by simon-xisystems** [deptofdefense/AndroidTacticalAssaultKit-CIV#103]
Hi, 

Would it possible to to allow the Third Party pipeline to support generating App Bundles as well as APK's? New Play Store restrictions means that only App bundles can be uploaded?

**Comment by takdeveloper** [comment]
@simon-xisystems We will look at this.

I'll leave the issue open to report updates,

**Comment by simon-xisystems** [comment]
@takdeveloper any updates on this?

**Comment by simon-xisystems** [comment]
@takdeveloper any updates on this?

**Comment by takdeveloper** [comment]
@simon-xisystems  The Third Party Pipeline through TAK.GOV added support for generation of AABs around the end of February. This feature is available by default; all successful runs will produce an AAB in addition to an APK.
