### ISSUE TITLE
Re-lock widget not working

### ISSUE THREAD

**Issue by matt-msi** [deptofdefense/AndroidTacticalAssaultKit-CIV#133]
The re-lock feature has an issue where sometimes it does not hold the lock.  After selecting the "Re-lock" button in the widget the previously locked item is locked, then after a second or two the lock is released and the map recenters on the self marker.

Steps to Reproduce:
1. Launch ATAK
2. Tap on any team/buddy marker
3. Radial menu appears
4. Tap on lock on friendly icon
5. Friendly icon is now locked at the center of the map
6. Tap on self marker
7. Radial menu appears
8. Re-lock menu appears on left side of the screen
9. Tap on the re-lock icon
10. Locked on friendly toast message appears
11. Map re-locks for 1 second, then changes the lock target back to the self marker (PROBLEM)

Hardware: Samsung Galaxy Tab A (8.0", 2019)
Model Number: SM-T290
OS: Android 11
Software: ATAK 4.3.0.0, ATAK 4.4.0.6 (2e7a914b

https://user-images.githubusercontent.com/84031230/137197851-5765d875-2732-4ad3-b3e9-5dd24520b013.mp4

**Comment by bisgroves** [comment]
Please let me know if this is now working in the latest release (4.5.1)?

**Comment by matt-msi** [comment]
Yes my team advised it is working in 4.5.1, I can also confirm the issue is resolved in 4.5.1.  Thanks.
