### ISSUE TITLE
4.5.0.1 drawing tools unusable in portrait mode

### ISSUE THREAD

**Issue by w111a** [deptofdefense/AndroidTacticalAssaultKit-CIV#153]
In portrait mode, when I select the drawing tools from the main menu, it is rendered behind the toolbar at the top of the screen making it unusable.  

![Screenshot_20211202-180821_ATAK](https://user-images.githubusercontent.com/6366424/144522433-b792430d-14da-4eee-865b-fc823db7a792.jpg)

It appears to render correctly in landscape view. 

![Screenshot_20211202-180911_ATAK](https://user-images.githubusercontent.com/6366424/144522498-350b0a94-350b-4390-be0a-8f47c156a1b5.jpg)

**Comment by bisgroves** [comment]
This is fixed and will be pushed as part of 4.5.1.

**Comment by bisgroves** [comment]
Please let us know if 4.5.1 from the playstore fixes the issue for you.

**Comment by w111a** [comment]
Yes, this appears to be fixed in 4.5.1.0. Thank you.

**Comment by w111a** [comment]
Fixed in 4.5.1
