### ISSUE TITLE
Version 4.5.0.1 bearing issue

### ISSUE THREAD

**Issue by nobodyinparticular1984** [deptofdefense/AndroidTacticalAssaultKit-CIV#155]
Hello there! Using ATAK on my mobile device (Sonim XP8800), but encountered persistent issue: bearing in personal LOCSTAT widget displays in degrees rather than mils even when I have ensured that the bearing unit is set correctly, and it displays mils everywhere else. Is there a workaround for this? I hope I'm not just being an idiot and haven't missed a setting somewhwere.
![Screenshot_20211228-172825](https://user-images.githubusercontent.com/96798019/147609192-3373135c-c237-491f-9110-ce11558c9147.png)

**Comment by bisgroves** [comment]
This has been filed in our internal ticketing system and will be looked at as a possible improvement for 4.6.

**Comment by nobodyinparticular1984** [comment]
> This has been filed in our internal ticketing system and will be looked at as a possible improvement for 4.6.

Looking forward to it! Thanks for the clarification.
