### ISSUE TITLE
deprecated transapps.mapi.MapView

### ISSUE THREAD

**Issue by L-Belluomini** [deptofdefense/AndroidTacticalAssaultKit-CIV#181]
compiling a plugin I am developing based on the plugin template, during the compile java with javac task, I get a note regarding the use of a deprecated API. 
I suppose i get this note from the interface "  transapps.mapi.MapView " that in the source code of the main app is marked as deprecated since 4.2 and will be removed in 4.5. 
based of the fact that I have compiled a plugin in the third party pipeline for civ 4.5.1. using said API, and that this plug in work correctly, I suppose there is some kind of mistake ? 
looking in the plugin example of the 4.5 release ( at the moment not merged in the main branch )  I see that the transapps.mapi.MapView is still used.
should I just go on using said API or I should change something ?

**Comment by takdeveloper** [comment]
@L-Belluomini Our deprecation markings are informative -- anything marked for removal at version X.Y should not be _expected_ to be available after that version and any existing calls should be migrated but sometimes we aren't able to remove in the stated version for various reasons.

As it relates specifically to `transapps.mapi.MapView`, please ensure that your plugin does not have functional dependency on that interface -- in other words your plugin maintains any interactions with the `com.atakmap.android.maps.MapView` class as opposed to the `transapps.mapi.MapView` interface. Assuming your plugin has adopted the basic boilerplate for `Lifecycle` and `Tool` that forward to `MapComponent` and `DropdownReceiver` there should be very little work required for migration when we do remove.

**Comment by L-Belluomini** [comment]
Thanks for the quick response, I think I solved the issue.
Just for reference, is there any documentation regarding alternatives for deprecated APIs I can look up in the future?
