### ISSUE TITLE
Gradle unexpectedly launching in odd mode

### ISSUE THREAD

**Issue by MightyBakedPotato** [deptofdefense/AndroidTacticalAssaultKit-CIV#184]
I'm using Android Studio as the IDE to work my plugin, but during sync gradle tries to build using the online mode (Configuring Maven TAK plugin build), and attempts all possible remote connections as if I had the Gitlab Devtools. 
I'm having this problem on windows only, as it works just fine on a Debian virtual machine (configuring Offline TakDev plugin build).
How do I fix this?

![Screenshot (195)](https://user-images.githubusercontent.com/99042539/155614622-14b55711-9867-4cb7-8f14-272fa5407aa9.png)

**Comment by takdeveloper** [comment]
@MightyBakedPotato The `atak-gradle-takdev` plugin should only reach out for remote dependencies if the ATAK SDK JAR file (main.jar) is not found locally.

Try explicitly specifying the location to the _directory containing the `main.jar` file_ via the Gradle property, `sdk.path`. Provided the file exists, this build should use the local dependency and not attempt to pull from remote.

You can inspect the logic here https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/blob/master/atak-gradle-takdev/src/main/groovy/com/atakmap/gradle/takdev/TakDevPlugin.groovy#L88
