### ISSUE TITLE
HelloWorld plugin does not sync gradle correctly for Android Studio

### ISSUE THREAD

**Issue by rob-baily** [deptofdefense/AndroidTacticalAssaultKit-CIV#188]
Using ATAK 4.4.0.15 and Android Studio Bumblebee 2021.1.1 Patch 2 when loading the HelloWorld plugin gradle fails with a cryptic error  like this:

> No signature of method: build_9ajwr7xgefoe0e0npxbj1fyyi.android() is applicable for argument types: (build_9ajwr7xgefoe0e0npxbj1fyyi$_run_closure3) values: [build_9ajwr7xgefoe0e0npxbj1fyyi$_run_closure3@1bb86d79]

Locally I corrected this by changing this line in the app/build.gradle:

**_def getValueFromPropertiesFile_**

to: 

**_ext.getValueFromPropertiesFile_**

I don't know if this is Android Studio issue because the syntax should be valid but it seems other things referenced outside the buildscript section are defined with ext.

**Comment by gilber78** [comment]
is there a similar fix for v 4.5.0.1?  the build gradle file seems different than what you suggest here to fix locally and i've configured local.properties, but the syntax I'm confused by in the gradle file is pasted below (starting line 122)

`signingConfigs {
        debug {
            def kf = getValueFromPropertiesFile(project.rootProject.file('local.properties'), 'takDebugKeyFile')
            def kfp = getValueFromPropertiesFile(project.rootProject.file('local.properties'), 'takDebugKeyFilePassword')
            def ka = getValueFromPropertiesFile(project.rootProject.file('local.properties'), 'takDebugKeyAlias')
            def kp = getValueFromPropertiesFile(project.rootProject.file('local.properties'), 'takDebugKeyPassword')`

to apply this fix do I do (for example) kf = ext.getValueFromPropertiesFile(. . .)?

**Comment by rob-baily** [comment]
This is still an issue for ATAK 4.5.0.1.  Used Android Studio Chipmunk 2021.2.1

**Comment by greg-hindley** [comment]
Which version of the Android Studio does the helloworld example sync correctly with?

**Comment by rob-baily** [comment]
@greg-hindley I am not aware of any version that it syncs with without making the change I mentioned.  I wanted to note the Android Studio version in case someone else found that it was working with some other version.

**Comment by rob-baily** [comment]
Confirmed in SDK 4.7.03 that it is no longer an issue.

**Comment by rob-baily** [comment]
@gitques I found if you create an account for tak.gov you can get access to some versions that are not in the open source repo yet.

**Comment by gitques** [comment]
@rob-baily  Thank you for your quick response. I am checking tak.gov now.
If you do not mind, could you please have a look [https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/issues/263#issue-1396718641](https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/issues/263#issue-1396718641)?
I am stuck here... I am not sure it can be resolved if I use another ATAK version..
