### ISSUE TITLE
Plugin Acceptable Signing Key Signature for NettWarrior/Raptor present in source code  

### ISSUE THREAD

**Issue by simon-xisystems** [deptofdefense/AndroidTacticalAssaultKit-CIV#2]
AtakPluginResistry.java still has the Acceptable plugin signing keys preset and labelled for Product Center Trusted, Nett Warrior and raptor. It might be worth removing either the code comments or the keys which would not be required by the open version of CivTAK.

**Comment by takdeveloper** [comment]
ATAK 4.1.0.0

In-line comments referring to signing key origins are removed, but the whitelist is retained.
