### ISSUE TITLE
Drone Image Location Resolution

### ISSUE THREAD

**Issue by mkrupczak3** [deptofdefense/AndroidTacticalAssaultKit-CIV#205]
Hi, 

I've been working on a program called [OpenAthena](https://github.com/mkrupczak3/OpenAthena) which finds the spot on the ground a drone is looking at, in any given photo, using terrain elevation data

[![pretty_good](https://user-images.githubusercontent.com/25494111/169142890-1c81d3c0-963b-4a60-8ebe-41561d3c49f3.jpg)](https://github.com/mkrupczak3/OpenAthena)

[![concept_whiteboard_diagram](https://user-images.githubusercontent.com/25494111/169142931-70180e9c-65f8-41a3-bc42-ccd4672fe952.jpg)](https://github.com/mkrupczak3/OpenAthena#premise)

I'd like to port this functionality to Java and integrate it with the ATAK app

Wondering if there's been any thought on this, or the best way to get started. 

Main hurdle for me to contribute would be an api to get terrain data from on an Android device
-Matthew

**Comment by mkrupczak3** [comment]
I'm willing to contribute code and wish to donate this concept and functionality to the ATAK app

**Comment by brothercorvo** [comment]
@mkrupczak3 this is corvo, from the [freeTAKTeam](https://github.com/FreeTAKTeam), you may want to look to our [FreeTAKUAS](https://github.com/FreeTAKTeam/FreeTAKServer-User-Docs/blob/main/docs/docs/tools/FreeTAKUAS.md) project
![image](https://user-images.githubusercontent.com/60719165/169578699-01786413-514a-4bd0-9555-0c2017d53f5c.png)
that is already featuring a simple algorithm to calculate a target on the ground, your code would be beneficial there.

**Comment by mkrupczak3** [comment]
Thanks for the referral, I'll take a look and see if I can get a PR in

**Comment by mkrupczak3** [comment]
@rdkgit 👀
