### ISSUE TITLE
Building plugintemplate - No signature of method ...

### ISSUE THREAD

**Issue by av-mario** [deptofdefense/AndroidTacticalAssaultKit-CIV#268]
Hi,

I'm following the legendary ATAK plugin 101 tutorial:
`https://www.ballantyne.online/developing-atak-plugin-101/`
but I have stumbled upon some issue which I am unable to resolve

``` bash
A problem occurred evaluating project ':app'.
> No signature of method: build_d3zoxwx0ukactzgeikmtgjpce.android() is applicable for argument types: (build_d3zoxwx0ukactzgeikmtgjpce$_run_closure2) values: [build_d3zoxwx0ukactzgeikmtgjpce$_run_closure2@42dee75d]
```

This is when I compile the app in plugintemplate, which corresponds to this function:

``` java
android {
    compileSdkVersion 26
    buildToolsVersion "30.0.2"

    dexOptions {
        jumboMode = true
    } 
...
}
```

I have my `local.properties` defined like this:
```
takDebugKeyAlias=androiddebugkey
sdk.dir=/home/mario/Android/Sdk
ndk.dir=/home/mario/android-ndk-r12b
cmake.dir=/home/mario/cmake-3.14.7-Linux-x86_64
takReleaseKeyAlias=androiddebugkey
takReleaseKeyPassword=android
takDebugKeyPassword=android
takReleaseKeyFilePassword=android
takReleaseKeyFile=/home/mario/Downloads/debug.keystore
takDebugKeyFilePassword=android

takDebugKeyFile=/home/mario/Downloads/debug.keystore
```

And I hardcoded the location of my `takdev`-jar.

Is there any hint in my code of what could be wrong?

As far as I have looked, the function might be getting called from somewhere with the wrong arguments? [Found here](https://stackoverflow.com/questions/17411209/how-to-fix-groovy-lang-missingmethodexception-no-signature-of-method)

I also do not see that the `app` is an app, but I think that is because the gradle failed?

e.g. in the tutorial it shows:

![Screenshot-2020-08-18-at-10 52 22](https://user-images.githubusercontent.com/116644708/200614453-6ef1b1f8-ea10-48fa-9b3e-56b9934db667.png)

but I see 

![image](https://user-images.githubusercontent.com/116644708/200615488-fea9ea58-c840-41c3-bb1d-381fb4236fe2.png)

Any hints here?

**Comment by av-mario** [comment]
#264

**Comment by av-mario** [comment]
On thing that brought me one step further is

` in build.gradle when it errors, go up to line 16 and change 'def ' to 'ext.`

**Comment by Hellikandra** [comment]
1. Have you created the *.jks ?

**Comment by sealfoss** [comment]
Did you ever find a solution to this? Setting up the symbolic link didn't solve the problem for me.

**Comment by sealfoss** [comment]
Never mind, changing instances of 'def' to 'ext.' was the solution.
