### ISSUE TITLE
pluginsdk.zip ## 4.1.1.2

### ISSUE THREAD

**Issue by peterhaigh** [deptofdefense/AndroidTacticalAssaultKit-CIV#27]
Hi
Changes to the build.gradle (Module: .....). means that the pluginsdk will not compile anymore in AndroidStudio, with the following error.

Deveopment/AndroidTacticalAssaultKit-CIV/atak/ATAK/plugin1/app/src/main/java/com/atakmap/android/plugintemplate/plugin/PluginTemplateTool.java:4: error: package com.atakmap.android.ipc does not exist

Is there any more information that needs to be set up before this will compile?

Thank you.

**Comment by takdeveloper** [comment]
@peterhaigh Can you please confirm the version of Android Studio that you're using. I verified that I am able to build `plugintemplate` without making any modifications, using the latest published release (`4.1.1.4`), in Android Studio 4.0. I also was able to build on the command-line without issue.

Below is a script which is used to sanity check the releases, can you please execute and see if your issue is reproduced? Note that it does require that `JAVA_HOME` is defined.

```bash
#!/bin/sh

# download release
curl -L -b -s https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/releases/download/4.1.1.4/atak-civ-sdk-4.1.1.4.zip --output atak-civ-sdk.zip
# unzip
unzip -q atak-civ-sdk.zip
# enter the plugintemplate dir
cd atak-civ/plugins/plugintemplate
# generate truststore
echo y | $JAVA_HOME/bin/keytool -genkeypair -dname "cn=ATAK Plugin, ou=, o=, c=US" -alias testbuild -keypass testbuild -keystore testbuild.jks -storepass testbuild -validity 10000
# generate local.properties
echo "takDebugKeyFile=../testbuild.jks" >> local.properties
echo "takDebugKeyFilePassword=testbuild" >> local.properties
echo "takDebugKeyAlias=testbuild" >> local.properties
echo "takDebugKeyPassword=testbuild" >> local.properties
echo "takReleaseKeyFile=../testbuild.jks" >> local.properties
echo "takReleaseKeyFilePassword=testbuild" >> local.properties
echo "takReleaseKeyAlias=testbuild" >> local.properties
echo "takReleaseKeyPassword=testbuild" >> local.properties
# build
./gradlew assembleCivDebug
```

**Comment by peterhaigh** [comment]
Hi 
It's clearly something I am doing wrong, your script worked perfectly.  I need to reassess my build workflow in android studio.  

Thank you again, for your help and time.

**Comment by takdeveloper** [comment]
I'm going to mark the issue as resolved, per your last comment. Please open a new issue if you're able to get more detail (e.g. if you can confirm that it appears to be an issue between different versions of Android Studio).
