### ISSUE TITLE
Can I build an Atak on Windows

### ISSUE THREAD

**Issue by xubinlu** [deptofdefense/AndroidTacticalAssaultKit-CIV#299]
https://www.ballantyne.online/build-an-atak-dev-environment/
I have read the above guide, but it is built on Linux. Can I build it on Windows

**Comment by Hellikandra** [comment]
You can build an atak plugin on Linux. The main guide provided by TPC use windows.

On an other hand, I am currently implementing Docker ATAK Dev : https://github.com/Hellikandra/ATAK-Dev-Docker

**Comment by xubinlu** [comment]
> You can build an atak plugin on Linux. The main guide provided by TPC use windows.
> 
> On an other hand, I am currently implementing Docker ATAK Dev : https://github.com/Hellikandra/ATAK-Dev-Docker

sorry，What do you mean by TPC, @Hellikandra

**Comment by Hellikandra** [comment]
TPC - TAK Product Center (tak.gov).
You can download SDK and you will have a quick guide to Android Studio + build a plugin template through Windows.

**Comment by kbtxwer** [comment]
> TPC - TAK Product Center (tak.gov). You can download SDK and you will have a quick guide to Android Studio + build a plugin template through Windows.

Is there a docker environment that I can run prebuild.sh and every thing is done?
