### ISSUE TITLE
Missing externals for Windows build.

### ISSUE THREAD

**Issue by kurtzmarc** [deptofdefense/AndroidTacticalAssaultKit-CIV#41]
We're trying to build the takengine in Windows using the new CMake scripts. It appears there are missing external packages. For instance the CMakeLists.txt in `/takengine` has:
```
# only for windows right now
if (WIN32)
    add_subdirectory (taktcm)
endif ()
```
However there is no taktcm folder. There are also various references to:
```
#ifdef MSVC
#include "vscompat.h"
#endif
```
However there is no vscompat.h file anywhere in the repo. I understand that a Windows build may not be officially supported, but is it possible to obtain or include these missing resources?

**Comment by takdeveloper** [comment]
Hi @kurtzmarc . These sources are not part of the open source distribution and will not be made available.
