### ISSUE TITLE
Open plugin's ToolPreference from DropDownReceiver

### ISSUE THREAD

**Issue by jonapoul** [deptofdefense/AndroidTacticalAssaultKit-CIV#43]
I'm not sure whether this is the best place to ask this, but I don't see any better forum to ask. Is there a way within the plugin SDK to directly open my plugin's registered preferences from a button?

For example, at the moment I can register a ToolPreference via the following, as ripped from the (extremely useful!) `helloworld` plugin example:
```
ToolsPreferenceFragment
                .register(
                        new ToolsPreferenceFragment.ToolPreference(
                                "Hello World Preferences",
                                "This is the sample preference for Hello World",
                                "helloWorldPreference",
                                context.getResources().getDrawable(
                                        R.drawable.ic_launcher, null),
                                new HelloWorldPreferenceFragment(context)));
```

And I can launch the Device, Network or Advanced settings respectively by calling:
```
AtakBroadcast.getInstance().sendBroadcast(Intent("com.atakmap.app.DEVICE_SETTINGS"))
AtakBroadcast.getInstance().sendBroadcast(Intent("com.atakmap.app.NETWORK_SETTINGS"))
AtakBroadcast.getInstance().sendBroadcast(Intent("com.atakmap.app.ADVANCED_SETTINGS"))
```

But I'd like to be able to directly open my registered ToolPreference without having to navigate through the menus manually. Is there a way of registering a custom intent string to let me do that? If not - it would be a welcome addition!

**Comment by bisgroves** [comment]
jonapaul, please see setAssociationKey("helloWorldPreference"); in HelloWorldDropDownReceiver which indicates that when the drop down is open, go ahead and open the associated preference.

**Comment by jonapoul** [comment]
@bisgroves That's great, thanks!
