### ISSUE TITLE
Osmdroid Sqlite tiles format

### ISSUE THREAD

**Issue by Techmaven-geospatial** [deptofdefense/AndroidTacticalAssaultKit-CIV#49]
How to convert MBTILES Raster Tiles to OSMDROID SQLite? Or Folder of TMS or XYZ png tiles to OSMDROID format that this app uses?
How are standard Tile Numbers (integers)
Zoom_level
Tile_Column
Tile_Row
Converted to KEY column?

Is the Tile (similar to tile_data blob) store same PNG/JPG/WEBP Image 256x256 or Multiples or is the Tile Blob different?

I can find documentation about this format
We have lots of mbtiles and want to convert them

**Comment by takdeveloper** [comment]
@Techmaven-geospatial The app supports MBtiles natively. Have you had issues importing your MBtiles datasets?

**Comment by Techmaven-geospatial** [comment]
I guess I never tried
Someone told me it only supported osmdroid
Is there a wiki page or readme with the filetypes it supports

**Comment by takdeveloper** [comment]
There's some info in here https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/blob/master/atak/ATAK/app/src/main/assets/support/README.txt (though it doesn't mention MBtiles!! Looks like it needs an update).

GDAL is integrated, so formats supported out of the box by GDAL should be supported in ATAK (see https://gdal.org/drivers/raster/index.html). We've written various custom parsers as well.

You can find the support code for handling the OSM Droid SQLilte containers here https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/blob/master/atak/ATAKMapEngine/lib/src/main/java/com/atakmap/map/layer/raster/osm/OSMDroidTileContainer.java.
