### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lok23** [deptofdefense/AndroidTacticalAssaultKit-CIV#58]
Hi, 
I'm a developer working on a plugin for ATAK.

Is there any documentation for the codebase?
I'm trying to get the user's current zoom level from the MapView.

Thanks!

**Comment by lok23** [comment]
Whoops, looks like you can get the current zoom level by doing MapView.getMapView().mapScale (for kotlin).

**Comment by takdeveloper** [comment]
@lok23 We do not currently provide any developer documentation for the open source distribution of ATAK. However, you can find examples of the most frequently used APIs in the helloworld plugin (https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/tree/master/plugin-examples/helloworld),

In addition to the method you've found, there is also `mapResolution`, which returns the current resolution in meters-per-pixel. We also include the utility, com.atakmap.map.layer.raster.osm.OSMUtils, which provides conversions between meters-per-pixel and OSM/google "slippy tile" zoom levels.
