### ISSUE TITLE
Missing tinygltfloader and tinygltf

### ISSUE THREAD

**Issue by sibi-ravindran** [deptofdefense/AndroidTacticalAssaultKit-CIV#6]
Hi, I am trying to compile ATAK-CIV according to Simon's blogpost https://www.ballantyne.online/?p=117

However, in the last step in building 'assembleCivDebug' I get the following errors 'fatal error: tinygltfloader/tiny_gltf_loader.h: No such file or directory' referred in GLTFrenderer_v1.cpp. I downloaded tinygltfloader from syoyo's github repository. I then had a similar error for tiny_gltf.h referred in GLTFRenderer_v2.cpp. I downloaded tiny_gltf from syoyo's github repository.

I now do not have the missing header files error. However, I get the following error '/home/sibi/AndroidTacticalAssaultKit-CIV/atak/ATAKMapEngine/lib/src/main/cpp/c3dt/GLTFv1.cpp:42:70: error: 'struct tinygltfloader::Image' has no member named 'uri'

Am I downloading the wrong tiny_gltf and tiny_gltf_loader? How do I get the correct sources for the tinygltf library? Thanks a lot.

**Comment by sibi-ravindran** [comment]
Found the libraries in 'depends' folder.

**Comment by peterhaigh** [comment]
Hi once you found the .gz .tar files in depends, where did you put them?  unzipped them and un tar'ed them and left them in the /depends folder but Android Studio still didn't find them

**Comment by takdeveloper** [comment]
@peterhaigh Please see the unpacking that is performed here https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/blob/master/scripts/prebuild.sh#L9. Those dependencies need to be located under `takengine/thirdparty` at build time.

**Comment by peterhaigh** [comment]
Thank you for your quick reply, I had to manually copy the files into takengine/thirdparty then everything worked well.  Do you know when the next release of ATAK-CIV is released, I saw on the open ATAK conference it was around the 12th December.  Thank you again.

**Comment by takdeveloper** [comment]
The latest version of ATAK CIV (4.2) is available now in the Google Play Store and from the TAK website landing page. We are pushing upstream updates to GitHub now for all of the 4.1.1.x builds; I anticipate the 4.2.0.x snapshots through current will be posted within the next two weeks.

**Comment by peterhaigh** [comment]
Fantastic congratulations to everyone working on the project.  It's an amazing bit of software.

**Comment by prajapak** [comment]
Hello, I am following the same example and also tried original and I am getting following error. Searched all over but no luck. Any help will be much appreciated.

`
Execution failed for task ':libtakengine:generateJsonModelCivDebug'.
> /home/ashok/StudioProjects/AndroidTacticalAssaultKit-CIV/takengine/takengine/CMakeLists.txt : C/C++ civDebug|armeabi-v7a : CMake Error at /home/ashok/StudioProjects/AndroidTacticalAssaultKit-CIV/takengine/takengine/cmake/support/conan.cmake:631 (message):
    Conan install failed='1'
  Call Stack (most recent call first):
    CMakeLists.txt:108 (conan_cmake_install)
`

**Comment by sunsongwen123** [comment]
> 

I also encountered this problem. How did you solve it
