### ISSUE TITLE
GPLv3 license

### ISSUE THREAD

**Issue by mbonness** [deptofdefense/AndroidTacticalAssaultKit-CIV#86]
Is it possible to convert the license to something more permissive like MIT or Apache 2.0?

Looking at your dependencies the only one that has a GPLv3 license is libstdc++, however if you look at the license terms for libstdc++ it has an exception that allows it to be used in proprietary software free of restrictions:

[https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html](url)

[https://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.license.any_program](url)

[https://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.license.what_restrictions](url)

**Comment by takdeveloper** [comment]
@mbonness We have no plans to convert from GPLv3 to a permissive license.
