### ISSUE TITLE
Bogus decimal degree accuracy

### ISSUE THREAD

**Issue by Cloud-RF** [deptofdefense/AndroidTacticalAssaultKit-CIV#88]
ATAK reports locations accurate to 15 decimal places, or 0.1 nano-meters.
This bogus accuracy becomes an issue when communicating routes over low bandwidth networks which may contain a large number of positions. 

For example, if you had 1000 points, that would be a minimum of 34 bytes per lat/lon pair eg. 0.12345678912345, 0.12345678912345 so 34KB in all.

If you reduced the resolution to 7 decimal places the same **information** could be conveyed with 18KB of **data**:
0.1234567, 0.1234567 = 18 bytes, accuracy 1.11cm (at the equator, less toward poles)

http://wiki.gis.com/wiki/index.php/Decimal_degrees

**Comment by takdeveloper** [comment]
@Cloud-RF Thank you for reporting this issue. In addition to truncating the stringified representation we may look at creating a protobuf definition.

**Comment by takdeveloper** [comment]
Resolved with 4.4.0.0 release.
