### ISSUE TITLE
Can I develop my plugin with JNI?

### ISSUE THREAD

**Issue by kbtxwer** [deptofdefense/AndroidTacticalAssaultKit-CIV#94]
I want to transplant an application as a plugin for ATAK, which dependes on JNI. Will it be ok for doing this?

**Comment by peterhaigh** [comment]
I'm using JNI in the plugin I'm developing with no issues.  The messaging protocol is written in C++ and is the same on the RasPi end and the ATAK Plugin end.

**Comment by takdeveloper** [comment]
One friendly tip for integrating JNI code: make sure you take care to add proguard rules to exclude any classes/methods/fields that you access via reflection from JNI.

Otherwise, as @peterhaigh said, you should be good to integrate any native library you'd like using JNI!

**Comment by kbtxwer** [comment]
Is there any official plugins that use JNI?
