### ISSUE TITLE
Build a plugin for ATAK Version number and above

### ISSUE THREAD

**Issue by peterhaigh** [deptofdefense/AndroidTacticalAssaultKit-CIV#96]
Hi takdeveloper, 

can I ask a quick question?  Can I build a plugin for an array of ATAK releases, v4.2, v4.3 v4.4 etc.  It's a user issue; if we create a plugin that will integrate with our hardware, do we have to issue a new plugin for each ATAK release, or can we specify say 4.x?   

I really appreciate any help you can provide.

**Comment by takdeveloper** [comment]
@peterhaigh we do not currently support targeting multiple versions of ATAK with a single plugin APK. You'll need to have a separate build for each version you are targeting.

**Comment by peterhaigh** [comment]
Thank you.
