### ISSUE TITLE
How can I locate the function that receives periodic positioning information

### ISSUE THREAD

**Issue by kbtxwer** [deptofdefense/AndroidTacticalAssaultKit-CIV#98]
I can only find functions like sendCoT(), but can not find anything receiveCoT()

**Comment by peterhaigh** [comment]
You need to register an InboundMessageHandler, have a look at Paul Mandel's youtube video and his ATAK forwarder plugin is on GitHub

**Comment by takdeveloper** [comment]
@kbtxwer @peterhaigh Please also see

https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/blob/master/atak/ATAK/app/src/main/java/com/atakmap/comms/CommsMapComponent.java#L553

The `CommsLogger` callback will be invoked whenever a CoT event is received on any network port. 

https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/blob/master/atak/ATAK/app/src/main/java/com/atakmap/android/cot/detail/CotDetailHandler.java
https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/blob/master/atak/ATAK/app/src/main/java/com/atakmap/android/cot/detail/CotDetailManager.java

If your intent is to mutate a `MapItem` based on details on a CoT event, you can register a `CotDetailHandler`, which will be invoked when the CoT event is being translated to a `MapItem`.

@kbtxwer If you've got a specific use-case that falls outside of what's described above, please provide some additional detail on what you're trying to accomplish.
