### ISSUE TITLE
java.lang.SecurityException: Permission Denial: starting intent

### ISSUE THREAD

**Issue by scordasco** [deptofdefense/AndroidTacticalAssaultKit-CIV#99]
I am trying to implement the Activity Recognition Transition API in an ATAK plugin. This API requires the ACTIVITY_RECOGNITION permission to be approved, however, is denied in ATAK.

In order to manually override it, I have attempted to start an activity within the onReceive() method in the PluginDropDownReceiver class.

val startIntent = Intent()
startIntent.setClassName(packageName, className)
startIntent.flags = Intent.FLAG_ACTIVITY_NEW_TASK
context.startActivity(startIntent)

This too fails with a SecurityException being thrown.

Is there a way to call startActivity(intent) in an ATAK plugin without a SecurityException being thrown?

**Comment by takdeveloper** [comment]
@scordasco In these kind of situations, what we normally suggest is to use a service to obtain any permissions not included with the ATAK runtime (since the plugin is constrained within the ATAK runtime). There are examples for bundling both activities and services in a plugin in the `helloworld` example.

Are you using the plugin `Context` or the main ATAK `Context` when trying to launch your activity?

**Comment by scordasco** [comment]
Thank you for your response. I will take a look at the helloworld example.

I am using the Context that is passed as an argument in the onReceive() method when trying to launch the activity.

**Comment by takdeveloper** [comment]
@scordasco That is the plugin context -- it's a special context ATAK instantiates to provide access to the plugin APK content. You can pull the main app context from `MapView.getContext()`. I'd try your snippet above with the app context also.

**Comment by scordasco** [comment]
Understood. Thank you again for your response. I'll give it a shot and report any results worth mentioning.

**Comment by takdeveloper** [comment]
Marking closed; @scordasco please feel free to add any comments on your results as applicable and interest permits
